server:
  servlet:
    contextPath: /store-management-service
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    url: /store-management-service/api-docs
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
  sql:
    init:
      data-locations:
      platform: h2